apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  .htpasswd: |
    {{ required "auth.htpasswd is required" .Values.auth.htpasswd }}
